name: "Lighthouse Badger"

permissions:
  contents: write   # 允许写回仓库（更新徽章/报告）

env:
  # 你的站点地址（建议：主页或需要打分的页面）
  URLS: https://zhengli-hub.github.io/
  # 目标仓库与分支：默认就是当前仓库和 main 分支
  REPO_BRANCH: "${{ github.repository }} main"
  MOBILE_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2"
  DESKTOP_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1"

on:
  workflow_dispatch:   # 手动触发
  # 如需定时触发，取消注释：
  # schedule:
  #   - cron: "0 8 * * 1"   # 每周一 08:00 运行

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        env:
          REPO_BRANCH: ${{ env.REPO_BRANCH }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}   # 改为内置 token
          ref: ${{ env.BRANCH }}

      - uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested

      - uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
