name: Build and Deploy al-folio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# ① 顶层权限（给 Pages 部署用）+ 并发控制（防止并发部署互相覆盖）
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ② 配置 Pages（官方动作，处理一些环境变量/权限）
      - uses: actions/configure-pages@v5

      # ③ 系统依赖（你启用了 jekyll-imagemagick 和 jekyll-terser）
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Setup Node (for terser)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install terser
        run: npm i -g terser

      # ④ Ruby & Bundler
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # ⑤ 构建（生产模式）
      - name: Bundle install
        run: bundle install --jobs 4

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      # ⑥ 上传 _site 给 Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
